version: "3"

services:
  backend:
    build:
      context: .
    image: hungergames-backend-image
    ports:
      - "8000:8000"
    volumes:
      - .:/app/src
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - database_network

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
