# Generated by Django 3.1.3 on 2020-11-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_flavors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
    ]
